# 应用名称
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: root
    password: '990628'
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: nginxDemo #服务名称
    servlet:
      multipart:
        max-file-size: 10MB


logging:
  level:
    root: info
    com.xhk.blog: debug
  file:
    name: log/blog-dev.log